title: Pragmatic Objects
subtitle: Pragmatic adaptation of "Elegant Objects" by Kapralov Sergey
scm: https://github.com/pragmatic-objects/site

collections:
  chapters:
      output: true

markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge

exclude:
- README.md
- node_modules
- _app
- "*.js"
- "*.json"

safe: true
lsi: false
