title: Pragmatic Objects
description: Pragmatic adaptation of Elegant Objects by Kapralov Sergey
scm: https://github.com/pragmatic-objects/site
url: https://pragmaticobjects.com

author:
  name: Kapralov Sergey

collections:
  chapters:
    output: true

markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge

exclude:
- README.md
- node_modules
- _app
- "*.js"
- "*.json"

safe: true
lsi: false
